name = "srp-worker"
main = "worker.js"
compatibility_date = "2024-09-01"

[[r2_buckets]]
binding = "DATA_BUCKET"
bucket_name = "chem112-results"

# Map the specific path to this Worker (adjust zone_name to your Cloudflare zone)
routes = [
  { pattern = "queenschem112srp.com/api/ingest", zone_name = "queenschem112srp.com" },
  { pattern = "queenschem112srp.com/api/ingest/*", zone_name = "queenschem112srp.com" }
]
